Fix some more DB envs.

diff --git a/contrib/db/env b/contrib/db/env
--- a/contrib/db/env
+++ b/contrib/db/env
@@ -2,14 +2,12 @@
 
 set -euo pipefail # exit on error; treat unset variables as errors; exit on errors in piped commands
 
-echo -n export DATABASE_URL=
-
 case ${1:-} in
   test)  echo $DATABASE_URL_TEST ;;
   stage) echo $DATABASE_URL_STAGE ;;
   prod)  echo $DATABASE_URL_PROD ;;
   *)
-    echo -e "\nERROR: Please provide as argument one of: test, stage, prod" >&2
+    echo -e "ERROR: Valid environments are: test, stage, prod" >&2
     exit 1
     ;;
 esac
